[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "*"
    Access-Control-Allow-Methods = "*"

[[redirects]]
  from = "/*"
  to = "/.netlify/edge-functions/proxy"
  status = 200
  force = true
